"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type Data = Record<string, string>;
type EventRecord = { id:number; name:string; client:string; venue:string; date:string; pax:number; status:string; amount:number; paid:number; costs:number };
type Field = { name:string; label:string; type?:"text"|"date"|"time"|"number"|"textarea"|"select"; options?:string[]; required?:boolean };
type Step = { title:string; hint:string; fields:Field[] };

const steps: Step[] = [
 {title:"Inicio y consentimiento",hint:"Inicia PLAUD y registra la autorización.",fields:[{name:"consentimiento",label:"Consentimiento para grabación",type:"select",options:["Sí, autoriza expresamente","No autoriza; tomar notas manuales"],required:true},{name:"fecha_entrevista",label:"Fecha de entrevista",type:"date"},{name:"entrevistador",label:"Entrevistador"}]},
 {title:"Cliente",hint:"Identifica a quien decide y puede solicitar cambios.",fields:[{name:"cliente",label:"Nombre y apellidos",required:true},{name:"telefono",label:"Teléfono"},{name:"correo",label:"Correo"},{name:"facturacion",label:"Empresa y datos de facturación",type:"textarea"},{name:"decisor",label:"Decisor final"},{name:"autorizados",label:"Personas autorizadas para cambios"},{name:"canal",label:"Canal preferido",type:"select",options:["WhatsApp","Teléfono","Correo electrónico"]}]},
 {title:"Visión del evento",hint:"Recoge la idea, los imprescindibles y lo que debe evitarse.",fields:[{name:"tipo",label:"Tipo de evento",type:"select",options:["Boda","Comunión","Bautizo","Cumpleaños","Aniversario","Corporativo","Presentación","Otro"],required:true},{name:"nombre_evento",label:"Nombre o referencia",required:true},{name:"vision",label:"¿Cómo imagináis el evento?",type:"textarea"},{name:"imprescindible",label:"Qué es imprescindible",type:"textarea"},{name:"evitar",label:"Qué queréis evitar",type:"textarea"},{name:"exito",label:"Para que fuera perfecto tendría que…",type:"textarea"}]},
 {title:"Fecha y cronograma",hint:"Define el local, espacio y horarios operativos.",fields:[{name:"fecha_evento",label:"Fecha solicitada",type:"date",required:true},{name:"fecha_alternativa",label:"Segunda fecha",type:"date"},{name:"local",label:"Local",type:"select",options:["Vive Roda","Olympic","Torre del Rame","Tapeoteca","Otro"],required:true},{name:"espacio",label:"Espacio o zonas"},{name:"hora_montaje",label:"Acceso montaje",type:"time"},{name:"hora_anfitriones",label:"Llegada anfitriones",type:"time"},{name:"hora_invitados",label:"Llegada invitados",type:"time"},{name:"hora_servicio",label:"Inicio servicio",type:"time"},{name:"hora_final",label:"Final previsto",type:"time"},{name:"actividad_previa",label:"Ceremonia o actividad previa",type:"textarea"}]},
 {title:"Asistentes",hint:"Dimensiona el servicio y fija la fecha de congelación.",fields:[{name:"adultos",label:"Adultos estimados",type:"number",required:true},{name:"ninos",label:"Niños estimados",type:"number"},{name:"minimo",label:"Mínimo previsto",type:"number"},{name:"maximo",label:"Máximo posible",type:"number"},{name:"perfil",label:"Bebés, mayores, movilidad o idiomas",type:"textarea"},{name:"accesibilidad",label:"Accesibilidad y atención especial",type:"textarea"},{name:"freeze_asistentes",label:"Fecha límite número final",type:"date",required:true}]},
 {title:"Presupuesto",hint:"Aterriza el alcance económico y los servicios incluidos.",fields:[{name:"presupuesto_persona",label:"Presupuesto por persona (€)",type:"number"},{name:"presupuesto_global",label:"Presupuesto global (€)",type:"number"},{name:"incluye",label:"Bebidas, decoración, música, audiovisuales…",type:"textarea"},{name:"servicios_cliente",label:"Servicios contratados por el cliente",type:"textarea"}]},
 {title:"Gastronomía",hint:"Información que alimentará la orden de cocina.",fields:[{name:"formato_gastro",label:"Formato",type:"select",options:["Menú sentado","Cóctel","Bufé","Mixto"]},{name:"menu",label:"Menú o platos deseados",type:"textarea"},{name:"no_productos",label:"Productos que no desean",type:"textarea"},{name:"ritmo",label:"Ritmo",type:"select",options:["Ágil","Normal","Pausado"]},{name:"momentos_platos",label:"Discursos o momentos entre platos",type:"textarea"},{name:"extra_gastro",label:"Infantil, tarta, recena, prueba…",type:"textarea"},{name:"alergias",label:"Alergias, intolerancias y dietas",type:"textarea",required:true},{name:"freeze_alergias",label:"Fecha límite del listado",type:"date"}]},
 {title:"Bebidas",hint:"Configura recepción, menú, cafés, brindis y barra.",fields:[{name:"bebidas",label:"Bebidas de recepción y menú",type:"textarea"},{name:"bar_servicios",label:"Cafés, brindis, barra y cócteles",type:"textarea"},{name:"bar_inicio",label:"Inicio barra",type:"time"},{name:"bar_fin",label:"Cierre barra",type:"time"},{name:"bar_condiciones",label:"Modalidad, límites y exclusiones",type:"textarea"},{name:"autoriza_ampliacion",label:"Quién autoriza ampliaciones"}]},
 {title:"Sala y decoración",hint:"Información para montaje, plano y seating.",fields:[{name:"distribucion",label:"Distribución",type:"select",options:["Mesas redondas","Mesas rectangulares","Imperiales","Cóctel","Mixta"]},{name:"montaje",label:"Pista, escenario, photocall, zona infantil…",type:"textarea"},{name:"plano",label:"Detalles del plano y seating",type:"textarea"},{name:"freeze_plano",label:"Fecha límite del plano",type:"date"},{name:"decoracion",label:"Estilo, colores y decoración",type:"textarea"},{name:"aportes",label:"Qué aporta cliente y local",type:"textarea"},{name:"elementos_especiales",label:"Elementos que requieren autorización",type:"textarea"}]},
 {title:"Música y proveedores",hint:"Recoge las necesidades técnicas y terceros.",fields:[{name:"av",label:"DJ, directo, micros, pantalla, iluminación…",type:"textarea"},{name:"necesidades_tecnicas",label:"Necesidades técnicas",type:"textarea"},{name:"limite_musica",label:"Horario y límite de música",type:"textarea"},{name:"proveedores",label:"Proveedores, contactos y horarios",type:"textarea"}]},
 {title:"Momentos y logística",hint:"Ordena protocolo, responsables y condicionantes.",fields:[{name:"protocolo",label:"Entrada, discursos, brindis, tarta, baile…",type:"textarea"},{name:"maestro_tiempos",label:"Persona que dará cada señal"},{name:"contacto_evento",label:"Interlocutor durante el evento"},{name:"seguridad",label:"Menores, seguridad o necesidades médicas",type:"textarea"},{name:"transporte",label:"Transporte, aparcamiento y alojamiento",type:"textarea"},{name:"discrecion",label:"Situaciones que requieren discreción",type:"textarea"}]},
 {title:"Cierre de entrevista",hint:"Define pagos, riesgos, pendientes y siguiente acción.",fields:[{name:"senal",label:"Señal: importe o porcentaje"},{name:"fecha_senal",label:"Fecha de señal",type:"date"},{name:"liquidacion",label:"Liquidación final",type:"date"},{name:"freeze_instructivo",label:"Congelación del instructivo",type:"date"},{name:"promesas",label:"Promesas o condiciones especiales",type:"textarea"},{name:"pendientes",label:"Decisiones pendientes",type:"textarea"},{name:"riesgos",label:"Riesgos o conflictos operativos",type:"textarea"},{name:"proxima_accion",label:"Próxima acción, responsable y fecha",type:"textarea",required:true}]}
];

export default function InterviewPanel({eventId,onEventUpdate}:{eventId:number;onEventUpdate:(event:EventRecord)=>void}){
 const [data,setData]=useState<Data>({}),[step,setStep]=useState(0),[state,setState]=useState("Cargando…"),[loaded,setLoaded]=useState(false),[saving,setSaving]=useState(false),[savedAt,setSavedAt]=useState("");
 const updateRef=useRef(onEventUpdate),dataRef=useRef(data),completionRef=useRef(0),dirtyRef=useRef(false);
 useEffect(()=>{updateRef.current=onEventUpdate},[onEventUpdate]);
 const required=useMemo(()=>steps.flatMap(s=>s.fields).filter(f=>f.required),[]);
 const completion=Math.round(required.filter(f=>String(data[f.name]??"").trim()).length/required.length*100);
 useEffect(()=>{dataRef.current=data;completionRef.current=completion},[data,completion]);
 const save=useCallback(async(payload:Data,percentage:number)=>{setSaving(true);setState("Guardando…");try{const response=await fetch(`/api/events/${eventId}/interview`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({payload,completion:percentage}),keepalive:true});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo guardar");dirtyRef.current=false;if(result.event)updateRef.current(result.event);const time=new Date().toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"});setSavedAt(time);setState("Guardado correctamente");return true}catch{setState("Error al guardar · pulsa Guardar ahora");return false}finally{setSaving(false)}},[eventId]);
 useEffect(()=>{let active=true;fetch(`/api/events/${eventId}/interview`,{cache:"no-store"}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error();return result}).then(result=>{if(!active)return;setData(result.interview?.payload??{});setSavedAt(result.interview?.updatedAt?new Date(result.interview.updatedAt).toLocaleTimeString("es-ES",{hour:"2-digit",minute:"2-digit"}):"");setState("Guardado automático activo")}).catch(()=>{if(active)setState("No se pudo cargar; puedes rellenar y guardar")}).finally(()=>{if(active)setLoaded(true)});return()=>{active=false}},[eventId]);
 useEffect(()=>{if(!loaded||!dirtyRef.current)return;const timer=window.setTimeout(()=>void save(data,completion),900);return()=>clearTimeout(timer)},[data,completion,loaded,save]);
 useEffect(()=>()=>{if(dirtyRef.current)void fetch(`/api/events/${eventId}/interview`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({payload:dataRef.current,completion:completionRef.current}),keepalive:true})},[eventId]);
 const current=steps[step],change=(name:string,value:string)=>{dirtyRef.current=true;setState("Cambios pendientes…");setData(old=>({...old,[name]:value}))};
 return <div className="interview-panel"><div className="interview-top"><div><p className="eyebrow">ENTREVISTA TÉCNICA · PLAUD EN PARALELO</p><h3>{current.title}</h3><p>{current.hint}</p></div><div className="interview-save"><strong>{completion}%</strong><small>{state}{savedAt?` · ${savedAt}`:""}</small><button type="button" className="mini" disabled={saving||!loaded} onClick={()=>void save(data,completion)}>{saving?"Guardando…":"Guardar ahora"}</button></div></div><div className="interview-progress"><i style={{width:`${completion}%`}}/></div><div className="interview-steps">{steps.map((s,i)=><button type="button" key={s.title} className={step===i?"active":""} onClick={()=>setStep(i)}><span>{i+1}</span>{s.title}</button>)}</div><div className="interview-fields">{current.fields.map(f=><label key={f.name} className={f.type==="textarea"?"wide":""}><span>{f.label}{f.required?" *":""}</span>{f.type==="textarea"?<textarea value={data[f.name]??""} onChange={e=>change(f.name,e.target.value)}/>:f.type==="select"?<select value={data[f.name]??""} onChange={e=>change(f.name,e.target.value)}><option value="">Seleccionar</option>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type??"text"} value={data[f.name]??""} onChange={e=>change(f.name,e.target.value)}/>}</label>)}</div><div className="interview-nav"><button type="button" className="secondary" disabled={!step} onClick={()=>setStep(v=>Math.max(0,v-1))}>← Anterior</button><span>Paso {step+1} de {steps.length}</span><button type="button" className="primary" disabled={step===steps.length-1} onClick={()=>setStep(v=>Math.min(steps.length-1,v+1))}>Siguiente →</button></div></div>
}
