import { sql } from "drizzle-orm";
import { integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const venues = sqliteTable("venues", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), active: integer("active", { mode: "boolean" }).notNull().default(true) });
export const clients = sqliteTable("clients", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull(), email: text("email"), phone: text("phone"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const events = sqliteTable("events", { id: integer("id").primaryKey({ autoIncrement: true }), clientId: integer("client_id").notNull(), venueId: integer("venue_id").notNull(), name: text("name").notNull(), eventDate: text("event_date").notNull(), guests: integer("guests").notNull().default(0), status: text("status").notNull().default("lead"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const budgets = sqliteTable("budgets", { id: integer("id").primaryKey({ autoIncrement: true }), eventId: integer("event_id").notNull(), version: integer("version").notNull().default(1), revenue: real("revenue").notNull().default(0), estimatedCost: real("estimated_cost").notNull().default(0), status: text("status").notNull().default("draft"), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) });
export const payments = sqliteTable("payments", { id: integer("id").primaryKey({ autoIncrement: true }), eventId: integer("event_id").notNull(), amount: real("amount").notNull(), dueDate: text("due_date").notNull(), paidAt: text("paid_at"), status: text("status").notNull().default("pending") });
export const tasks = sqliteTable("tasks", { id: integer("id").primaryKey({ autoIncrement: true }), eventId: integer("event_id").notNull(), title: text("title").notNull(), owner: text("owner").notNull(), dueDate: text("due_date"), priority: text("priority").notNull().default("medium"), completed: integer("completed", { mode: "boolean" }).notNull().default(false) });
export const serviceOrders = sqliteTable("service_orders", { id: integer("id").primaryKey({ autoIncrement: true }), eventId: integer("event_id").notNull(), department: text("department").notNull(), instructions: text("instructions").notNull().default(""), status: text("status").notNull().default("draft"), approvedAt: text("approved_at") });
export const closures = sqliteTable("closures", { id: integer("id").primaryKey({ autoIncrement: true }), eventId: integer("event_id").notNull(), actualRevenue: real("actual_revenue").notNull().default(0), actualCost: real("actual_cost").notNull().default(0), notes: text("notes").notNull().default(""), closedAt: text("closed_at") });
